apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/app-sre/git-partition-sync-consumer-master?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "20"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch == "master"
  labels:
    appstudio.openshift.io/application: git-partition-sync-consumer-master
    appstudio.openshift.io/component: git-partition-sync-consumer-master
    pipelines.appstudio.openshift.io/type: build
  name: git-partition-sync-consumer-master-on-push
  namespace: app-sre-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/app-sre-tenant/git-partition-sync-consumer-master/git-partition-sync-consumer-master:{{revision}}
  - name: dockerfile
    value: Dockerfile
  - name: path-context
    value: .
  - name: target-stage
    value: prod
  pipelineRef:
    resolver: git
    params:
    - name: url
      value: https://github.com/app-sre/shared-pipelines
    - name: revision
      value: main
    - name: pathInRepo
      value: pipelines/multi-arch-build-pipeline.yaml
  taskRunTemplate:
    serviceAccountName: build-pipeline-git-partition-sync-consumer-master
  workspaces:
  - name: workspace
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'