apiVersion: v1
kind: Template
metadata:
  name: git-partition-sync-consumer
objects:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: git-partition-sync-consumer
    annotations:
      ignore-check.kube-linter.io/minimum-three-replicas: "git-partition-sync-consumer design does not adequately account for multiple replicas"
      ignore-check.kube-linter.io/no-readiness-probe: "git-partition-sync-consumer does not receive traffic"
      ignore-check.kube-linter.io/unset-cpu-requirements: "no cpu limits"
    name: git-partition-sync-consumer
  spec:
    replicas: ${{REPLICAS}}
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 0
        maxSurge: 1
    selector:
      matchLabels:
        app: git-partition-sync-consumer
    template:
      metadata:
        labels:
          app: git-partition-sync-consumer
          component: qontract-reconcile
      spec:
        serviceAccountName: git-partition-sync-consumer
        containers:
        - image: ${IMAGE}:${IMAGE_TAG}
          imagePullPolicy: Always
          name: git-partition-sync-consumer
          args: ["-dry-run=${DRY_RUN}", "-run-once=${RUN_ONCE}"]
          env:
          - name: RECONCILE_SLEEP_TIME
            value: ${RECONCILE_SLEEP_TIME}
          - name: WORKDIR
            value: ${VOLUME_PATH}/${WORKDIR}
          - name: INTERNAL_GIT_CA_PATH
            value: ${INTERNAL_GIT_CA_PATH}
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                key: aws.access.key.id
                name: ${VAULT_SECRET_NAME}
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                key: aws.secret.access.key
                name: ${VAULT_SECRET_NAME}
          - name: AWS_REGION
            valueFrom:
              secretKeyRef:
                key: aws.region
                name: ${VAULT_SECRET_NAME}
          - name: AWS_S3_BUCKET
            valueFrom:
              secretKeyRef:
                key: aws.s3.bucket
                name: ${VAULT_SECRET_NAME}
          - name: GITLAB_BASE_URL
            valueFrom:
              secretKeyRef:
                key: gitlab.url
                name: ${VAULT_SECRET_NAME}
          - name: GITLAB_USERNAME
            valueFrom:
              secretKeyRef:
                key: gitlab.username
                name: ${VAULT_SECRET_NAME}
          - name: GITLAB_TOKEN
            valueFrom:
              secretKeyRef:
                key: gitlab.token
                name: ${VAULT_SECRET_NAME}
          - name: PRIVATE_KEY
            valueFrom:
              secretKeyRef:
                key: private.key
                name: ${VAULT_SECRET_NAME}
          resources:
            requests:
              memory: ${MEMORY_REQUESTS}
              cpu: ${CPU_REQUESTS}
            limits:
              memory: ${MEMORY_LIMIT}
          volumeMounts:
          - name: sync-ops
            mountPath: ${VOLUME_PATH}
          - name: ca-certs
            mountPath: ${INTERNAL_GIT_CA_PATH}
            subPath: ca.crt
        volumes:
        - name: sync-ops
          emptyDir: {}
        - name: ca-certs
          secret:
            secretName: ca-certs
            items:
            - key: ca.crt
              path: ca.crt
parameters:
- name: IMAGE
  value: quay.io/app-sre/git-partition-sync-consumer
  displayName: git-partition-sync-consumer image
  description: git-partition-sync-consumer docker image. Defaults to quay.io/app-sre/git-partition-sync-consumer
- name: IMAGE_TAG
  value: latest
  displayName: git-partition-sync-consumer version
  description: git-partition-sync-consumer version which defaults to latest
- name: RECONCILE_SLEEP_TIME
  value: '15m'
- name: DRY_RUN
  description: runs vault-manager in dry-run mode when true
  value: 'true'
- name: RUN_ONCE
  description: exits after one reconciliation attempt when true
  value: 'false'
- name: VOLUME_PATH
  value: '/sync-ops'
- name: WORKDIR
  value: 'working'
- name: REPLICAS
  value: '1'
- name: MEMORY_REQUESTS
  value: 1000Mi
- name: MEMORY_LIMIT
  value: 1000Mi
- name: CPU_REQUESTS
  value: 300m
- name: VAULT_SECRET_NAME
  value: git-partition-sync-consumer
- name: INTERNAL_GIT_CA_PATH
  description: 'path to certificate file to add in git config trust'
  value: '/etc/pki/ca-trust/source/anchors/ca.crt'
